// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/comprehension/file.proto

package comprehension

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataChunk struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataChunk) Reset()         { *m = DataChunk{} }
func (m *DataChunk) String() string { return proto.CompactTextString(m) }
func (*DataChunk) ProtoMessage()    {}
func (*DataChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e5a1b4a6a5c01ff, []int{0}
}

func (m *DataChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataChunk.Unmarshal(m, b)
}
func (m *DataChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataChunk.Marshal(b, m, deterministic)
}
func (m *DataChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataChunk.Merge(m, src)
}
func (m *DataChunk) XXX_Size() int {
	return xxx_messageInfo_DataChunk.Size(m)
}
func (m *DataChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_DataChunk.DiscardUnknown(m)
}

var xxx_messageInfo_DataChunk proto.InternalMessageInfo

func (m *DataChunk) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Submission struct {
	SubmissionId         string   `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	VariantId            string   `protobuf:"bytes,2,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	Language             string   `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Code                 []string `protobuf:"bytes,4,rep,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Submission) Reset()         { *m = Submission{} }
func (m *Submission) String() string { return proto.CompactTextString(m) }
func (*Submission) ProtoMessage()    {}
func (*Submission) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e5a1b4a6a5c01ff, []int{1}
}

func (m *Submission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Submission.Unmarshal(m, b)
}
func (m *Submission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Submission.Marshal(b, m, deterministic)
}
func (m *Submission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Submission.Merge(m, src)
}
func (m *Submission) XXX_Size() int {
	return xxx_messageInfo_Submission.Size(m)
}
func (m *Submission) XXX_DiscardUnknown() {
	xxx_messageInfo_Submission.DiscardUnknown(m)
}

var xxx_messageInfo_Submission proto.InternalMessageInfo

func (m *Submission) GetSubmissionId() string {
	if m != nil {
		return m.SubmissionId
	}
	return ""
}

func (m *Submission) GetVariantId() string {
	if m != nil {
		return m.VariantId
	}
	return ""
}

func (m *Submission) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Submission) GetCode() []string {
	if m != nil {
		return m.Code
	}
	return nil
}

type Response struct {
	Received             bool     `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e5a1b4a6a5c01ff, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetReceived() bool {
	if m != nil {
		return m.Received
	}
	return false
}

func init() {
	proto.RegisterType((*DataChunk)(nil), "comprehension.DataChunk")
	proto.RegisterType((*Submission)(nil), "comprehension.Submission")
	proto.RegisterType((*Response)(nil), "comprehension.Response")
}

func init() {
	proto.RegisterFile("proto/comprehension/file.proto", fileDescriptor_7e5a1b4a6a5c01ff)
}

var fileDescriptor_7e5a1b4a6a5c01ff = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x51, 0x4b, 0xf3, 0x30,
	0x14, 0xfd, 0xfa, 0x6d, 0x48, 0x7b, 0xb7, 0xbd, 0x04, 0xc1, 0x3a, 0x50, 0x47, 0x05, 0xe9, 0x53,
	0x07, 0xf3, 0x1f, 0xe8, 0x10, 0x8a, 0x2f, 0x9a, 0xbd, 0xf9, 0x22, 0x59, 0x72, 0xdd, 0x82, 0x6d,
	0x52, 0x92, 0xb4, 0xbe, 0xfa, 0xd3, 0x25, 0x71, 0x76, 0x6e, 0xe0, 0xdb, 0xbd, 0xe7, 0x9c, 0x7b,
	0x4f, 0xee, 0x09, 0x5c, 0x36, 0x46, 0x3b, 0x3d, 0xe7, 0xba, 0x6e, 0x0c, 0x6e, 0x51, 0x59, 0xa9,
	0xd5, 0xfc, 0x4d, 0x56, 0x58, 0x04, 0x82, 0x4c, 0x0e, 0x98, 0xec, 0x0a, 0x92, 0x25, 0x73, 0xec,
	0x7e, 0xdb, 0xaa, 0x77, 0x42, 0x60, 0x28, 0x98, 0x63, 0x69, 0x34, 0x8b, 0xf2, 0x31, 0x0d, 0x75,
	0xf6, 0x19, 0x01, 0xac, 0xda, 0x75, 0x2d, 0xad, 0xd7, 0x93, 0x6b, 0x98, 0xd8, 0xbe, 0x7b, 0x95,
	0x22, 0x68, 0x13, 0x3a, 0xde, 0x83, 0xa5, 0x20, 0x17, 0x00, 0x1d, 0x33, 0x92, 0x29, 0xe7, 0x15,
	0xff, 0x83, 0x22, 0xd9, 0x21, 0xa5, 0x20, 0x53, 0x88, 0x2b, 0xa6, 0x36, 0x2d, 0xdb, 0x60, 0x3a,
	0x08, 0x64, 0xdf, 0xfb, 0x27, 0x70, 0x2d, 0x30, 0x1d, 0xce, 0x06, 0x79, 0x42, 0x43, 0x9d, 0xdd,
	0x40, 0x4c, 0xd1, 0x36, 0x5a, 0x59, 0xf4, 0xb3, 0x06, 0x39, 0xca, 0x0e, 0xbf, 0xad, 0x63, 0xda,
	0xf7, 0x8b, 0x17, 0x18, 0xf9, 0x43, 0x57, 0x68, 0x3a, 0xc9, 0x91, 0x3c, 0xc2, 0xe9, 0x52, 0x7f,
	0xa8, 0x4a, 0x33, 0xf1, 0x64, 0xb4, 0x68, 0xb9, 0x2b, 0x6b, 0x6f, 0x91, 0x16, 0x07, 0x11, 0x14,
	0xfd, 0xfd, 0xd3, 0xb3, 0x23, 0xe6, 0xc7, 0x35, 0x8f, 0x16, 0xcf, 0x30, 0x7a, 0xf8, 0xb5, 0xfb,
	0x6e, 0x17, 0x8a, 0xf3, 0x20, 0x39, 0x3f, 0x9a, 0xdb, 0xe7, 0xf5, 0xe7, 0xca, 0xec, 0xdf, 0xfa,
	0x24, 0x7c, 0xc8, 0xed, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x48, 0x95, 0xdc, 0x5a, 0xb2, 0x01,
	0x00, 0x00,
}
