// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: proto/comprehension/file.proto

package comprehension

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BasicCodeFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BasicCodeFile) Reset() {
	*x = BasicCodeFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comprehension_file_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicCodeFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicCodeFile) ProtoMessage() {}

func (x *BasicCodeFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comprehension_file_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicCodeFile.ProtoReflect.Descriptor instead.
func (*BasicCodeFile) Descriptor() ([]byte, []int) {
	return file_proto_comprehension_file_proto_rawDescGZIP(), []int{0}
}

func (x *BasicCodeFile) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SubmittedCodeFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data         []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	SubmissionId string `protobuf:"bytes,2,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
}

func (x *SubmittedCodeFile) Reset() {
	*x = SubmittedCodeFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comprehension_file_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmittedCodeFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmittedCodeFile) ProtoMessage() {}

func (x *SubmittedCodeFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comprehension_file_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmittedCodeFile.ProtoReflect.Descriptor instead.
func (*SubmittedCodeFile) Descriptor() ([]byte, []int) {
	return file_proto_comprehension_file_proto_rawDescGZIP(), []int{1}
}

func (x *SubmittedCodeFile) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SubmittedCodeFile) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

type VariantCodeFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data         []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	SubmissionId string `protobuf:"bytes,2,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	VariantId    string `protobuf:"bytes,3,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
}

func (x *VariantCodeFile) Reset() {
	*x = VariantCodeFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comprehension_file_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VariantCodeFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariantCodeFile) ProtoMessage() {}

func (x *VariantCodeFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comprehension_file_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariantCodeFile.ProtoReflect.Descriptor instead.
func (*VariantCodeFile) Descriptor() ([]byte, []int) {
	return file_proto_comprehension_file_proto_rawDescGZIP(), []int{2}
}

func (x *VariantCodeFile) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VariantCodeFile) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *VariantCodeFile) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

type VariableDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *VariableDetail) Reset() {
	*x = VariableDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comprehension_file_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VariableDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableDetail) ProtoMessage() {}

func (x *VariableDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comprehension_file_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableDetail.ProtoReflect.Descriptor instead.
func (*VariableDetail) Descriptor() ([]byte, []int) {
	return file_proto_comprehension_file_proto_rawDescGZIP(), []int{3}
}

func (x *VariableDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VariableDetail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *VariableDetail) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SingleCalculation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order       int32  `protobuf:"varint,1,opt,name=order,proto3" json:"order,omitempty"`
	Explanation string `protobuf:"bytes,2,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Code        string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Result      string `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Type        string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *SingleCalculation) Reset() {
	*x = SingleCalculation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comprehension_file_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleCalculation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleCalculation) ProtoMessage() {}

func (x *SingleCalculation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comprehension_file_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleCalculation.ProtoReflect.Descriptor instead.
func (*SingleCalculation) Descriptor() ([]byte, []int) {
	return file_proto_comprehension_file_proto_rawDescGZIP(), []int{4}
}

func (x *SingleCalculation) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *SingleCalculation) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *SingleCalculation) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SingleCalculation) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *SingleCalculation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type MultiCalculation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LineNumber  string            `protobuf:"bytes,1,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	Explanation string            `protobuf:"bytes,2,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Code        string            `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Result      string            `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Type        string            `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Vars        []*VariableDetail `protobuf:"bytes,6,rep,name=vars,proto3" json:"vars,omitempty"`
	NextLine    string            `protobuf:"bytes,7,opt,name=next_line,json=nextLine,proto3" json:"next_line,omitempty"`
}

func (x *MultiCalculation) Reset() {
	*x = MultiCalculation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comprehension_file_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiCalculation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiCalculation) ProtoMessage() {}

func (x *MultiCalculation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comprehension_file_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiCalculation.ProtoReflect.Descriptor instead.
func (*MultiCalculation) Descriptor() ([]byte, []int) {
	return file_proto_comprehension_file_proto_rawDescGZIP(), []int{5}
}

func (x *MultiCalculation) GetLineNumber() string {
	if x != nil {
		return x.LineNumber
	}
	return ""
}

func (x *MultiCalculation) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *MultiCalculation) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MultiCalculation) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *MultiCalculation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MultiCalculation) GetVars() []*VariableDetail {
	if x != nil {
		return x.Vars
	}
	return nil
}

func (x *MultiCalculation) GetNextLine() string {
	if x != nil {
		return x.NextLine
	}
	return ""
}

type SingleLineQuestion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentLine  string               `protobuf:"bytes,1,opt,name=current_line,json=currentLine,proto3" json:"current_line,omitempty"`
	NextLine     string               `protobuf:"bytes,2,opt,name=next_line,json=nextLine,proto3" json:"next_line,omitempty"`
	VarsBefore   []*VariableDetail    `protobuf:"bytes,3,rep,name=vars_before,json=varsBefore,proto3" json:"vars_before,omitempty"`
	Calculations []*SingleCalculation `protobuf:"bytes,4,rep,name=calculations,proto3" json:"calculations,omitempty"`
	VarsAfter    []*VariableDetail    `protobuf:"bytes,5,rep,name=vars_after,json=varsAfter,proto3" json:"vars_after,omitempty"`
}

func (x *SingleLineQuestion) Reset() {
	*x = SingleLineQuestion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comprehension_file_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleLineQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleLineQuestion) ProtoMessage() {}

func (x *SingleLineQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comprehension_file_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleLineQuestion.ProtoReflect.Descriptor instead.
func (*SingleLineQuestion) Descriptor() ([]byte, []int) {
	return file_proto_comprehension_file_proto_rawDescGZIP(), []int{6}
}

func (x *SingleLineQuestion) GetCurrentLine() string {
	if x != nil {
		return x.CurrentLine
	}
	return ""
}

func (x *SingleLineQuestion) GetNextLine() string {
	if x != nil {
		return x.NextLine
	}
	return ""
}

func (x *SingleLineQuestion) GetVarsBefore() []*VariableDetail {
	if x != nil {
		return x.VarsBefore
	}
	return nil
}

func (x *SingleLineQuestion) GetCalculations() []*SingleCalculation {
	if x != nil {
		return x.Calculations
	}
	return nil
}

func (x *SingleLineQuestion) GetVarsAfter() []*VariableDetail {
	if x != nil {
		return x.VarsAfter
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Received     bool     `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	SubmissionId string   `protobuf:"bytes,2,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	VariantId    []string `protobuf:"bytes,3,rep,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comprehension_file_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comprehension_file_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_comprehension_file_proto_rawDescGZIP(), []int{7}
}

func (x *Response) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *Response) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *Response) GetVariantId() []string {
	if x != nil {
		return x.VariantId
	}
	return nil
}

var File_proto_comprehension_file_proto protoreflect.FileDescriptor

var file_proto_comprehension_file_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x68, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x68, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0x23, 0x0a, 0x0d, 0x42, 0x61, 0x73, 0x69, 0x63, 0x43, 0x6f, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x4c, 0x0a, 0x11, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x74, 0x65,
	0x64, 0x43, 0x6f, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x23, 0x0a,
	0x0d, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x22, 0x69, 0x0a, 0x0f, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x62,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x4e, 0x0a,
	0x0e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x8b, 0x01,
	0x0a, 0x11, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78, 0x70,
	0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x65, 0x78, 0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xe5, 0x01, 0x0a, 0x10,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x76, 0x61, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x68, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x52, 0x04, 0x76, 0x61, 0x72, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x6c,
	0x69, 0x6e, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x65, 0x78, 0x74, 0x4c,
	0x69, 0x6e, 0x65, 0x22, 0x98, 0x02, 0x0a, 0x12, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4c, 0x69,
	0x6e, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6e, 0x65, 0x78, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x76, 0x61,
	0x72, 0x73, 0x5f, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x68, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e,
	0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0a,
	0x76, 0x61, 0x72, 0x73, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x12, 0x44, 0x0a, 0x0c, 0x63, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x68, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0c, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x3c, 0x0a, 0x0a, 0x76, 0x61, 0x72, 0x73, 0x5f, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x68, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x09, 0x76, 0x61, 0x72, 0x73, 0x41, 0x66, 0x74, 0x65, 0x72, 0x22, 0x6a,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73,
	0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x76,
	0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x32, 0x56, 0x0a, 0x0b, 0x46, 0x69,
	0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1c, 0x2e, 0x63, 0x6f,
	0x6d, 0x70, 0x72, 0x65, 0x68, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x61, 0x73, 0x69,
	0x63, 0x43, 0x6f, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x1a, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x70,
	0x72, 0x65, 0x68, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0x5f, 0x0a, 0x0e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x12, 0x20, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x72,
	0x65, 0x68, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x74,
	0x65, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x1a, 0x17, 0x2e, 0x63, 0x6f, 0x6d,
	0x70, 0x72, 0x65, 0x68, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0x54, 0x0a, 0x0a, 0x41, 0x53, 0x54, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x46, 0x0a, 0x0b, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x41, 0x53, 0x54,
	0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x68, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x65,
	0x1a, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x68, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x58, 0x0a, 0x0c, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x6d,
	0x70, 0x72, 0x65, 0x68, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61,
	0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x1a, 0x17, 0x2e, 0x63, 0x6f, 0x6d,
	0x70, 0x72, 0x65, 0x68, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_comprehension_file_proto_rawDescOnce sync.Once
	file_proto_comprehension_file_proto_rawDescData = file_proto_comprehension_file_proto_rawDesc
)

func file_proto_comprehension_file_proto_rawDescGZIP() []byte {
	file_proto_comprehension_file_proto_rawDescOnce.Do(func() {
		file_proto_comprehension_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_comprehension_file_proto_rawDescData)
	})
	return file_proto_comprehension_file_proto_rawDescData
}

var file_proto_comprehension_file_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_comprehension_file_proto_goTypes = []interface{}{
	(*BasicCodeFile)(nil),      // 0: comprehension.BasicCodeFile
	(*SubmittedCodeFile)(nil),  // 1: comprehension.SubmittedCodeFile
	(*VariantCodeFile)(nil),    // 2: comprehension.VariantCodeFile
	(*VariableDetail)(nil),     // 3: comprehension.VariableDetail
	(*SingleCalculation)(nil),  // 4: comprehension.SingleCalculation
	(*MultiCalculation)(nil),   // 5: comprehension.MultiCalculation
	(*SingleLineQuestion)(nil), // 6: comprehension.SingleLineQuestion
	(*Response)(nil),           // 7: comprehension.Response
}
var file_proto_comprehension_file_proto_depIdxs = []int32{
	3, // 0: comprehension.MultiCalculation.vars:type_name -> comprehension.VariableDetail
	3, // 1: comprehension.SingleLineQuestion.vars_before:type_name -> comprehension.VariableDetail
	4, // 2: comprehension.SingleLineQuestion.calculations:type_name -> comprehension.SingleCalculation
	3, // 3: comprehension.SingleLineQuestion.vars_after:type_name -> comprehension.VariableDetail
	0, // 4: comprehension.FileService.SubmitCodeFile:input_type -> comprehension.BasicCodeFile
	1, // 5: comprehension.VariantService.GenerateVariants:input_type -> comprehension.SubmittedCodeFile
	2, // 6: comprehension.ASTService.GenerateAST:input_type -> comprehension.VariantCodeFile
	2, // 7: comprehension.ImageService.GenerateImage:input_type -> comprehension.VariantCodeFile
	7, // 8: comprehension.FileService.SubmitCodeFile:output_type -> comprehension.Response
	7, // 9: comprehension.VariantService.GenerateVariants:output_type -> comprehension.Response
	7, // 10: comprehension.ASTService.GenerateAST:output_type -> comprehension.Response
	7, // 11: comprehension.ImageService.GenerateImage:output_type -> comprehension.Response
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_comprehension_file_proto_init() }
func file_proto_comprehension_file_proto_init() {
	if File_proto_comprehension_file_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_comprehension_file_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasicCodeFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comprehension_file_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmittedCodeFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comprehension_file_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VariantCodeFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comprehension_file_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VariableDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comprehension_file_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleCalculation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comprehension_file_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiCalculation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comprehension_file_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleLineQuestion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comprehension_file_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_comprehension_file_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_comprehension_file_proto_goTypes,
		DependencyIndexes: file_proto_comprehension_file_proto_depIdxs,
		MessageInfos:      file_proto_comprehension_file_proto_msgTypes,
	}.Build()
	File_proto_comprehension_file_proto = out.File
	file_proto_comprehension_file_proto_rawDesc = nil
	file_proto_comprehension_file_proto_goTypes = nil
	file_proto_comprehension_file_proto_depIdxs = nil
}
